### ISSUE TITLE
laravel5.5下的一些问题

### ISSUE THREAD

**Issue by asundust** [Cydmi/JdLM#1]
laravel5.5下报错
Class 'JD\Exception' not found，你的代码的确是没有Exception这个类，将JdClient.php:89代码改成new \Exception 可以解决（多了“\”）。
Class 'JD\LtLogger' not found，这个应该是你自己定义的一个类，麻烦亲提供一下。
另外JdClient.php:89 的 public $serverUrl = "http://gw.api.360buy.net/routerjson"; 正确地址应该为 public $serverUrl = "http://api.jd.com/routerjson";
刚刚发现你的1和2问题是已经解决了的，但是还没有发布新的版本。第三个问题是存在的。

**Comment by Cydmi** [comment]
@asundust 感谢你的反馈。 第三个问题在创建实例的时候可以 设置的。
京东有些代码是基于第三方框架写的，里面一些遇到的代码已经清除。版本近期会更新。
```
$c=new JdClient();
$c->serverUrl = "https://api.jd.com/routerjson";
```
